efill_app/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from efill_app import views

urlpatterns = [
	url(r'^home/$', views.home, name='home_page'),
    url(r'^form1/$', views.itr_form_view, name='itr_form_view'),
]

efill_tax/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from efill_app import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^efile/', include('efill_app.urls')),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
]

efill_app/models.py
from django.db import models
from django.conf import settings
from datetime import date

# Create your models here.

class PersonalInfo(models.Model):
	pan_number = models.CharField(max_length = 10, primary_key = True)
	first_name = models.CharField(max_length = 25, blank = True)
	middle_name = models.CharField(max_length = 25, blank = True)
	last_name = models.CharField(max_length = 25, default = "")
	flat_no = models.CharField(max_length = 5, default = " ")
	premise_name = models.CharField(max_length = 15, blank = True)
	road_name = models.CharField(max_length = 10, blank = True)
	area_name = models.CharField(max_length = 15, default = " ")
	city_name = models.CharField(max_length = 15, default = " ")
	state_name = models.CharField(max_length = 20, default = " ")
	country_name = models.CharField(max_length = 20, default = " ")
	pincode = models.CharField(max_length = 6, default = " ")
	martial_status = models.CharField(max_length = 10, default = "Unmarried")
	dob = models.DateField(default=date.today) 
	sex  = models.CharField(max_length = 6, default = "Male")
	email_id = models.CharField(max_length = 25, default = " ")
	mobile_1 = models.CharField(max_length = 10, default = " ")
	mobile_2 = models.CharField(max_length = 10, blank = True)
	std_code = models.CharField(max_length = 5, blank = True)
	phone_no = models.CharField(max_length = 8, blank = True)
	employer_category = models.CharField(max_length = 3, default = 'OTH')

	def __str__():
		return pan_number

efill_app/forms.py
from django import forms
from efill_app.models import PersonalInfo

class PersonalInfoForm(forms.models.ModelForm):
	class Meta:
		model = PersonalInfo
		fields = ('pan_number', )
		widgets = {
			'text': forms.fields.TextInput(attrs={
			'placeholder': 'Enter a to-do item',
			'class': 'form-control input-lg',
			}),
		}

efill_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from efill_app.forms import PersonalInfoForm
from django.http import HttpResponse
from efill_app.models import PersonalInfo
from django.core.exceptions import ValidationError
from django.db import IntegrityError, DataError
import re
# Create your views here.



def login(request):
	if request.user.is_authenticated():
		logout(request)
	return render(request, 'login.html')

@login_required(login_url='/')	
def home(request):
	return render(request, 'base.html')

@login_required(login_url='/')
def itr_form_view(request):
	error = None
	if request.method == 'POST':
		error = test_all(request)

	return render(request, 'ITRform.html',{'error': error})

def logout(request):
    auth_logout(request)
    return redirect('/')


def test_all(request):
	error = {}
	error['pan'] = validate_pan_number(request)
	error['last_name'] = validate_last_name(request)
	error['first_name'] = validate_first_name(request)
	error['middle_name'] = validate_middle_name(request)
	return error

def validate_pan_number(request):
	error = None
	pan_number = request.POST['pan_number']
	if not re.match(r'^[A-Z]{5}[0-9A-Z]{5}$',pan_number):
		error = "Invalid PAN number"
		return error
	#else: #PersonalInfo.objects.filter(pan_number = pan_number):
		#return error
	return error

def validate_last_name(request):
	error = None
	last_name = request.POST['last_name']
	if not re.match(r'^[A-Za-z]{1,25}$', last_name):
		error = "Enter a valid last name"
		return error
	else:
		return error

def validate_first_name(request):
	error = None
	first_name = request.POST['first_name']
	if re.match(r'^[A-Za-z]{1,25}$', first_name) or first_name == "":
		return error
	else:
		error = "Enter a valid first name"
		return error

def validate_middle_name(request):
	error = None
	middle_name = request.POST['middle_name']
	if re.match(r'^[A-Za-z]{1,25}$', middle_name) or middle_name == "":
		return error
	else:
		error = "Enter a valid middle name"
		return error

	

efill_app/templates/base.html
{% load staticfiles %}

{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}


<html>
<head>
{% block head %}
	<meta charset="utf-8">
	<meta  name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" type="text/css" href="{% static "css/custom.css" %}">
	<!--NAV BAR-->
	<div>
		<div class="row">
			<nav class="navbar navbar-fixed-top" role = "navigation">
				<nav class="navbar navbar-inverse">
				  	<div class="container-fluid">
				  	<div class="row">
				  		<ul class="nav navbar-nav">
				  			<li><img src="{% static "images/ITR.jpg" %}" height="40" width="40" style="margin-left: 10px; margin-top: 10px"/></li>
					    	<li style="margin-top: 8px "><a href="/efile/home/" style="color: white ; font-family: monospace; font-size: 25px">INCOME TAX RETURN</a></li>
 
					    </ul>
					    	<ul class="nav navbar-nav navbar-right">
					      <li class="dropdown">
						        <a class="dropdown-toggle" data-toggle="dropdown" href="#" style="margin-right: 50px; font-family: monospace; font-size: 15px; margin-top: 8px ; color: white;">
						        Welcome {{user.first_name}}
						        <span class="caret"></span></a>
						        <ul class="dropdown-menu">
						          <li><a href="/logout/">Logout</a></li>
						        </ul>
					      	</li>
					    </ul>
				  	</div>

				  	<div class="row">
				  		<div class="container">
					    <ul class="nav navbar-nav">
					      	<li><a href="#" style="color: white">Summary and Status</a></li>
					      	<li><a href="/efile/form1/" style="color: white">Personal Information</a></li>
							<li><a href="#" style="color: white">Salary Information</a></li>
							<li><a href="#" style="color: white">House and Property</a></li>
							<li><a href="#" style="color: white">Business or Profession</a></li>
							<li><a href="#" style="color: white">Capital Gains</a></li>
							<li><a href="#" style="color: white">Other Sources</a></li>
					    </ul>
					    </div>
					</div>
				</nav>
			</nav>
		</div>
	</div>
{% endblock %}
</head>
<body>
{% block body %}
	<img src="{% static "images/emblemofindia.png" %}" class="img-responsive center-block">
{% endblock %}
	<!--javascript-->
	<script type="text/javascript" src="http://code.jquery.com/jquery-3.1.1.min.js"></script>
	<script type="text/javascript" src="//code.jquery.com/jquery-latest.min.js"></script>
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
	<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
	<script>
	$('a.btn-danger').tooltip()
	</script>
</body>
</html>

efill_app/templates/login.html
<!--login.html-->
{# Load the tag library #}
{% load bootstrap3 %}
{% load staticfiles %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

<!DOCTYPE html>
<html>
<head>
	<title>Log in</title>
</head>
<body style="background-color: #6c6c6c">
	<div class="row" style="padding: 80px"></div>

	<div class="row">
		<div class="col-md-4"></div>

		<div class="col-md-4">
			<div class="panel panel-primary">
				<div class="panel-heading" style="background-color: #286dd2">
					<center><h3>LOGO</h3></center>
				</div>
				<div class="panel-body" >
					<div class="row text-center" style="padding-left: 30px; padding-right: 30px;">
						<h4><b>Income Tax Return Form</b></h4>
					</div>
					<div class="row text-center" style="background-color: #f7f7f7; padding-top: 10px;">
						<h5>Log in with your email id</h5>
					</div>
					<div class="row" style="padding-bottom: 10px; padding-top: 20px; background-color: #f7f7f7;">
						<center><a href="{% url 'social:begin' 'google-oauth2' %}?next=/efile/home/" class="btn btn-danger btn-lg" style="background-color: #bb1225">Log In</a></center>
					</div>
					{% if user and not user.is_anonymous %}
						<h1>HELLO</h1>
					{% endif %}
				</div>	
			</div>
		</div>
		<div class="col-md-4"></div>
	</div>
</body>
</html>, 

efill_app/templates/try.html
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>
  <style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;}
.tg td{font-family:Arial, sans-serif;font-size:14px;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;}
.tg th{font-family:Arial, sans-serif;font-size:14px;font-weight:normal;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;}
.tg .tg-446s{font-weight:bold;text-decoration:underline;font-size:26px;background-color:#ffccc9;text-align:center;vertical-align:top}
.tg .tg-w1ms{background-color:#ffffff;color:#333333;vertical-align:top}
.tg .tg-4bw1{font-weight:bold;background-color:#ffffff;color:#333333;text-align:center;vertical-align:top}
.tg .tg-4jb6{background-color:#ffffff;color:#333333;text-align:center;vertical-align:top}
.tg .tg-fbrz{font-weight:bold;font-size:20px;text-align:center;vertical-align:top}
.tg .tg-3we0{background-color:#ffffff;vertical-align:top}
.tg .tg-3b2a{font-weight:bold;font-size:20px;background-color:#ffffff;text-align:center;vertical-align:top}
.tg .tg-5j4b{font-weight:bold;background-color:#ffffff;text-align:center;vertical-align:top}
</style>
<table class="tg" style="undefined;table-layout: fixed; width: 1310px">
<colgroup>
<col style="width: 287px">
<col style="width: 429px">
<col style="width: 285px">
<col style="width: 309px">
</colgroup>
  <tr>
    <th class="tg-446s" colspan="4">INDIVIDUAL INCOME TAX RETURN<br></th>
  </tr>
  <tr>
    <td class="tg-fbrz" colspan="4">PERSONAL INFORMATION</td>
  </tr>
  <tr>
    <td class="tg-4bw1">First name</td>
    <td class="tg-4bw1">Middle name</td>
    <td class="tg-4bw1">Last name</td>
    <td class="tg-4bw1">PAN</td>
  </tr>
  <tr>
    <td class="tg-4jb6"><input name="pan_number" id="id_pan_number" placeholder="Enter PAN number" class="form-control"/></td>
    <td class="tg-4jb6"></td>
    <td class="tg-4jb6"></td>
    <td class="tg-4jb6"></td>
  </tr>
  <tr>
    <td class="tg-4bw1">Sex</td>
    <td class="tg-4bw1">Date of birth (format: dd/mm/yyy)</td>
    <td class="tg-4bw1" colspan="2">Area / Locality</td>
  </tr>
  <tr>
    <td class="tg-4jb6"></td>
    <td class="tg-4jb6"></td>
    <td class="tg-4jb6" colspan="2"></td>
  </tr>
  <tr>
    <td class="tg-4bw1">Flat / Door / Building</td>
    <td class="tg-4bw1">Name of Premises / Building / Village</td>
    <td class="tg-4bw1">Road / Street</td>
    <td class="tg-4bw1">Pincode</td>
  </tr>
  <tr>
    <td class="tg-4jb6"></td>
    <td class="tg-4jb6"></td>
    <td class="tg-4jb6"></td>
    <td class="tg-4jb6"></td>
  </tr>
  <tr>
    <td class="tg-4bw1">Town/ City/ District</td>
    <td class="tg-4bw1">State</td>
    <td class="tg-4bw1">Country</td>
    <td class="tg-4bw1">Employer Category</td>
  </tr>
  <tr>
    <td class="tg-4jb6"></td>
    <td class="tg-4jb6"></td>
    <td class="tg-4jb6"></td>
    <td class="tg-4jb6"></td>
  </tr>
  <tr>
    <td class="tg-4bw1">Status</td>
    <td class="tg-4bw1">Email Address</td>
    <td class="tg-4bw1">Mobile No. 1</td>
    <td class="tg-4bw1">Mobile No. 2</td>
  </tr>
  <tr>
    <td class="tg-4jb6"></td>
    <td class="tg-4jb6"></td>
    <td class="tg-4jb6"></td>
    <td class="tg-4jb6"></td>
  </tr>
  <tr>
    <td class="tg-4bw1">STD code</td>
    <td class="tg-4bw1">Phone number (Landline)</td>
    <td class="tg-w1ms"></td>
    <td class="tg-w1ms"></td>
  </tr>
  <tr>
    <td class="tg-w1ms"></td>
    <td class="tg-w1ms"></td>
    <td class="tg-w1ms"></td>
    <td class="tg-w1ms"></td>
  </tr>
  <tr>
    <td class="tg-4bw1" colspan="4">FILING STATUS</td>
  </tr>
  <tr>
    <td class="tg-4bw1">Whether Person governed by Portuguese Civil Code under section 5A ?</td>
    <td class="tg-4bw1">PAN of spouse</td>
    <td class="tg-4bw1">Tax Status</td>
    <td class="tg-4bw1">Whether it is original or revised return?</td>
  </tr>
  <tr>
    <td class="tg-w1ms"></td>
    <td class="tg-w1ms"></td>
    <td class="tg-w1ms"></td>
    <td class="tg-w1ms"></td>
  </tr>
  <tr>
    <td class="tg-4bw1">If Revised/Defective, then Enter Receipt Number of Original Return</td>
    <td class="tg-4bw1">Notice No (Where the Original Return filed was defective and a notice is issued to the assessee to file a fresh return Sec 139(9)</td>
    <td class="tg-4bw1">Date of Filing Original Return</td>
    <td class="tg-4bw1">If filed in response to a notice u/s 139(9)/142(1)/148/153A/153C enter date of such notice</td>
  </tr>
  <tr>
    <td class="tg-w1ms"></td>
    <td class="tg-w1ms"></td>
    <td class="tg-w1ms"></td>
    <td class="tg-w1ms"></td>
  </tr>
  <tr>
    <td class="tg-4bw1">Residential Status</td>
    <td class="tg-4bw1">Whether you have Aadhaar Number?</td>
    <td class="tg-4bw1" colspan="2">If Yes, Please provide Aadhaar Number</td>
  </tr>
  <tr>
    <td class="tg-w1ms"></td>
    <td class="tg-w1ms"></td>
    <td class="tg-w1ms" colspan="2"></td>
  </tr>
  <tr>
    <td class="tg-4jb6">Income tax ward/circle</td>
    <td class="tg-4bw1">Return filed under section</td>
    <td class="tg-w1ms"></td>
    <td class="tg-w1ms"></td>
  </tr>
  <tr>
    <td class="tg-w1ms"></td>
    <td class="tg-w1ms"></td>
    <td class="tg-3we0"></td>
    <td class="tg-3we0"></td>
  </tr>
  <tr>
    <td class="tg-3b2a" colspan="4">INCOME &amp; DEDUCTIONS</td>
  </tr>
  <tr>
    <td class="tg-5j4b">1) Income from Salary / Pension (Ensure to fill Sch TDS1)</td>
    <td class="tg-5j4b">2) Income from One House Property</td>
    <td class="tg-5j4b">3) Income from Other Sources (Ensure to fill Sch TDS2)</td>
    <td class="tg-5j4b">Gross Total Income (1+2+3)</td>
  </tr>
  <tr>
    <td class="tg-3we0"></td>
    <td class="tg-3we0"></td>
    <td class="tg-3we0"></td>
    <td class="tg-3we0"></td>
  </tr>
  <tr>
    <td class="tg-3we0"></td>
    <td class="tg-3we0"></td>
    <td class="tg-3we0"></td>
    <td class="tg-3we0"></td>
  </tr>
</table>

</body>
</html>